spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
  messages:
    basename: i18n.login

